// Clerk
import { ClerkProvider } from "@clerk/nextjs";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";

// Providers
import { TrpcProvider } from "./providers/trpc-provider/trpc-provider";

// Styles
import "./globals.css";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <ClerkProvider>
            {/* <TrpcProvider> */}
                <html lang="en" className="h-full">
                    <body
                        className={`flex flex-col min-h-screen ${inter.className}`}
                    >
                        <header className="w-full text-center py-10 bg-blue-600 text-white">
                            <h1 className="text-4xl font-bold">
                                Welcome to Our App
                            </h1>
                            <p className="mt-2 text-lg">
                                Your one-stop solution for job searching
                            </p>
                        </header>

                        <main className="flex-grow flex flex-col p-10 items-center justify-between bg-gray-100 w-full">
                            {children}
                        </main>

                        <footer className="w-full text-center py-4 bg-blue-600 text-white">
                            <p>&copy; 2023 Our App. All rights reserved.</p>
                        </footer>
                    </body>
                </html>
            {/* </TrpcProvider> */}
        </ClerkProvider>
    );
}
