import { ClerkProvider, SignedIn, UserButton } from '@clerk/nextjs';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
// Providers
import { TrpcProvider } from './providers/trpc-provider/trpc-provider';
// Styles
import './globals.css';

const inter = Inter({
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={inter.className}>
                    <header>
                        <SignedIn>
                            <UserButton />
                        </SignedIn>
                    </header>

                    <TrpcProvider>{children}</TrpcProvider>
                </body>
            </html>
        </ClerkProvider>
    );
}
